parameters:
#    app_site.example.class: AdminBundle\Example

services:
    app.admin.admin.user:
        class: AdminBundle\Admin\UserAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: Administration, label: Users }
        arguments: [null, AppBundle\Entity\User, SonataAdminBundle:CRUD]
        calls:
            - [ setTranslationDomain, [AdminBundle]]
#            - [ setSecurityTokenStorage , ["@security.token_storage"]]
    app.admin.admin.jobtype:
            class: AdminBundle\Admin\JobTypeAdmin
            tags:
                - { name: sonata.admin, manager_type: orm, group: Jobs, label: JobTypes }
            arguments: [null, AppBundle\Entity\JobType, SonataAdminBundle:CRUD]
            calls:
                - [ setTranslationDomain, [AdminBundle]]
    app.admin.admin.job:
            class: AdminBundle\Admin\JobAdmin
            tags:
                - { name: sonata.admin, manager_type: orm, group: Jobs, label: Jobs }
            arguments: [null, AppBundle\Entity\Job, SonataAdminBundle:CRUD]
            calls:
                - [ setTranslationDomain, [AdminBundle]]
